/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class LanguageService {
  constructor()
  open(uri: string, source: string): void
  update(uri: string, source: string): boolean
  close(uri: string): boolean
  registerModule(name: string, source: string): void
  registerHostFunction(name: string, params: Array<NapiHostFunctionParameter>, returns: string, documentation?: string | undefined | null, asyncFn?: boolean | undefined | null): void
  registerRuntimeShape(name: string, shapeJson: string, lastValueJson?: string | undefined | null): boolean
  complete(uri: string, offset: number): Array<NapiCompletion>
  hover(uri: string, offset: number): NapiHover | null
  diagnostics(uri: string): Array<NapiDiagnostic>
}

export declare class Vm {
  constructor()
  run(source: string): string
  /**
   * Lex and parse module source without evaluating it or resolving imports.
   *
   * This uses the same lexer and parser as execution. In particular, it
   * does not register or run the module, invoke host functions, or apply
   * side effects. Callers can use it to decide whether optional source
   * transformation is needed before registration.
   */
  validateModule(source: string): ValidationResult
  /**
   * Define a guest module *without* evaluating it.
   *
   * The body runs the first time something imports the module. Deferring it
   * is what makes a cyclic import graph expressible: define every module in
   * the cycle, then import any one of them, and each body runs once with
   * the partner's partially-populated exports visible through live
   * bindings — which is what the ES module specification describes.
   *
   * `registerModule` remains the eager form, and reports a body's error at
   * registration time; with `defineModule` the error surfaces at the import.
   */
  defineModule(name: string, source: string): void
  /**
   * Register (or replace) a guest module.
   *
   * Registration is transactional over the module's export table: the body
   * evaluates into a fresh export record, and that record replaces the
   * previous one only once evaluation succeeds. A body that throws leaves
   * the previously registered version of the module exactly as it was,
   * rather than a half-populated one.
   *
   * The transaction covers exports, not global side effects. A body that
   * assigns a global and *then* throws leaves that global set; unwinding
   * arbitrary interpreter state is not something this layer can promise.
   * Callers who need that isolation should use a fresh `Vm`.
   */
  registerModule(name: string, source: string): void
  /**
   * Register a module whose exports are host functions.
   *
   * This is the generic half of `exposeFunction` + `registerModule`: the
   * core bridges each function to a hidden global and generates the wrapper
   * module that re-exports it. What those functions *do* — including any
   * permission checks — stays entirely on the host side.
   *
   * Returns the generated global names so the host can tear them down with
   * `removeGlobal` when it removes the module.
   */
  registerHostModule(name: string, exports: Record<string, Function>, options?: { async?: Array<string> }): Array<string>
  /**
   * Release the host resources this VM holds, deterministically.
   *
   * A VM that has run `runAsync` owns a threadsafe-function for dispatching
   * host calls, and that handle keeps the N-API environment -- and so the
   * Node process -- alive. Dropping the `Vm` releases it, but a `Vm` held in
   * a module-level binding is never dropped, so a script that used
   * `runAsync` would hang at exit instead of returning to the shell.
   *
   * Calling this is idempotent and safe while an async worker is still in
   * flight: handles are marked retired and the last in-flight callback
   * releases them. After it returns, host functions are no longer callable
   * from guest code.
   */
  dispose(): void
  setImportMetaMain(isMain: boolean): void
  /** Cap the number of loop iterations in a single execution. */
  setLoopLimit(n: number): void
  getGlobal(name: string): string
  setGlobal(name: string, value: unknown): void
  exposeFunction(name: string, func: unknown): void
  exposeAsyncFunction(name: string, func: unknown): void
  /**
   * Execute code that may await host functions. The worker captures only
   * the `Arc<VMState>`; the interpreter itself remains under `RuntimeCell`'s
   * mutex and is never accessed concurrently with a Node method.
   */
  runAsync(source: string): Promise<string>
  /**
   * Unregister a module, making it unresolvable to `import` and revoking
   * any bridge globals a `registerHostModule` created for it.
   *
   * This is the capability-revocation primitive: after it returns, guest
   * code that imports `name` gets `Module not found`, and host functions
   * the module exported are no longer reachable through any binding it
   * installed. Bindings a *previous* execution already imported into a
   * global keep the value they captured -- revocation applies to
   * resolution, not to references the guest already holds.
   *
   * Returns whether anything was registered under `name`.
   */
  removeModule(name: string): boolean
  /**
   * Whether `name` is registered. This never disagrees with what `import`
   * can resolve: registration and removal move the source registry and the
   * interpreter's export table together.
   */
  hasModule(name: string): boolean
  listModules(): Array<string>
  removeGlobal(name: string): boolean
  hasGlobal(name: string): boolean
  callFunction(name: string, args: Array<unknown>): unknown
}
export type VM = Vm

export declare function createVm(): Vm

export declare function debugParse(source: string): string

export interface NapiCompletion {
  label: string
  kind: string
  detail?: string
}

export interface NapiDiagnostic {
  line: number
  col: number
  message: string
  severity: string
}

export interface NapiHostFunctionParameter {
  name: string
  typeName: string
}

export interface NapiHover {
  detail: string
  documentation?: string
}

export declare function runCode(source: string): string

/** One parse-only diagnostic returned by `VM.validateModule`. */
export interface ValidationDiagnostic {
  line: number
  column: number
  message: string
  kind: "syntax" | "unsupported-syntax" | "parse-limit"
}

/** Result of lexing and parsing guest source without executing it. */
export interface ValidationResult {
  valid: boolean
  diagnostics: Array<ValidationDiagnostic>
}
