//! The Node-API function table and its property descriptor layout.

use super::*;

#[repr(C)]
pub(super) struct NapiVmApiTable {
    pub(super) get_undefined: unsafe extern "C" fn(NapiEnv, *mut NapiValue) -> i32,
    pub(super) get_global: unsafe extern "C" fn(NapiEnv, *mut NapiValue) -> i32,
    pub(super) get_null: unsafe extern "C" fn(NapiEnv, *mut NapiValue) -> i32,
    pub(super) get_boolean: unsafe extern "C" fn(NapiEnv, bool, *mut NapiValue) -> i32,
    pub(super) coerce_to_bool: unsafe extern "C" fn(NapiEnv, NapiValue, *mut NapiValue) -> i32,
    pub(super) coerce_to_number: unsafe extern "C" fn(NapiEnv, NapiValue, *mut NapiValue) -> i32,
    pub(super) coerce_to_string: unsafe extern "C" fn(NapiEnv, NapiValue, *mut NapiValue) -> i32,
    pub(super) create_double: unsafe extern "C" fn(NapiEnv, f64, *mut NapiValue) -> i32,
    pub(super) create_int32: unsafe extern "C" fn(NapiEnv, i32, *mut NapiValue) -> i32,
    pub(super) create_uint32: unsafe extern "C" fn(NapiEnv, u32, *mut NapiValue) -> i32,
    pub(super) create_int64: unsafe extern "C" fn(NapiEnv, i64, *mut NapiValue) -> i32,
    pub(super) create_string_latin1:
        unsafe extern "C" fn(NapiEnv, *const c_char, usize, *mut NapiValue) -> i32,
    pub(super) create_string_utf8:
        unsafe extern "C" fn(NapiEnv, *const c_char, usize, *mut NapiValue) -> i32,
    pub(super) create_string_utf16:
        unsafe extern "C" fn(NapiEnv, *const u16, usize, *mut NapiValue) -> i32,
    pub(super) create_symbol: unsafe extern "C" fn(NapiEnv, NapiValue, *mut NapiValue) -> i32,
    pub(super) create_external: unsafe extern "C" fn(
        NapiEnv,
        *mut c_void,
        Option<NapiFinalize>,
        *mut c_void,
        *mut NapiValue,
    ) -> i32,
    pub(super) typeof_value: unsafe extern "C" fn(NapiEnv, NapiValue, *mut i32) -> i32,
    pub(super) get_value_external:
        unsafe extern "C" fn(NapiEnv, NapiValue, *mut *mut c_void) -> i32,
    pub(super) get_value_double: unsafe extern "C" fn(NapiEnv, NapiValue, *mut f64) -> i32,
    pub(super) get_value_int32: unsafe extern "C" fn(NapiEnv, NapiValue, *mut i32) -> i32,
    pub(super) get_value_uint32: unsafe extern "C" fn(NapiEnv, NapiValue, *mut u32) -> i32,
    pub(super) get_value_int64: unsafe extern "C" fn(NapiEnv, NapiValue, *mut i64) -> i32,
    pub(super) get_value_bool: unsafe extern "C" fn(NapiEnv, NapiValue, *mut bool) -> i32,
    pub(super) get_value_string_latin1:
        unsafe extern "C" fn(NapiEnv, NapiValue, *mut c_char, usize, *mut usize) -> i32,
    pub(super) get_value_string_utf8:
        unsafe extern "C" fn(NapiEnv, NapiValue, *mut c_char, usize, *mut usize) -> i32,
    pub(super) get_value_string_utf16:
        unsafe extern "C" fn(NapiEnv, NapiValue, *mut u16, usize, *mut usize) -> i32,
    pub(super) create_array: unsafe extern "C" fn(NapiEnv, *mut NapiValue) -> i32,
    pub(super) create_array_with_length:
        unsafe extern "C" fn(NapiEnv, usize, *mut NapiValue) -> i32,
    pub(super) is_array: unsafe extern "C" fn(NapiEnv, NapiValue, *mut bool) -> i32,
    pub(super) get_array_length: unsafe extern "C" fn(NapiEnv, NapiValue, *mut u32) -> i32,
    pub(super) get_prototype: unsafe extern "C" fn(NapiEnv, NapiValue, *mut NapiValue) -> i32,
    pub(super) get_element: unsafe extern "C" fn(NapiEnv, NapiValue, u32, *mut NapiValue) -> i32,
    pub(super) set_element: unsafe extern "C" fn(NapiEnv, NapiValue, u32, NapiValue) -> i32,
    pub(super) has_element: unsafe extern "C" fn(NapiEnv, NapiValue, u32, *mut bool) -> i32,
    pub(super) create_buffer:
        unsafe extern "C" fn(NapiEnv, usize, *mut *mut c_void, *mut NapiValue) -> i32,
    pub(super) create_buffer_copy: unsafe extern "C" fn(
        NapiEnv,
        usize,
        *const c_void,
        *mut *mut c_void,
        *mut NapiValue,
    ) -> i32,
    pub(super) get_buffer_info:
        unsafe extern "C" fn(NapiEnv, NapiValue, *mut *mut c_void, *mut usize) -> i32,
    pub(super) is_buffer: unsafe extern "C" fn(NapiEnv, NapiValue, *mut bool) -> i32,
    pub(super) is_arraybuffer: unsafe extern "C" fn(NapiEnv, NapiValue, *mut bool) -> i32,
    pub(super) create_arraybuffer:
        unsafe extern "C" fn(NapiEnv, usize, *mut *mut c_void, *mut NapiValue) -> i32,
    pub(super) get_arraybuffer_info:
        unsafe extern "C" fn(NapiEnv, NapiValue, *mut *mut c_void, *mut usize) -> i32,
    pub(super) is_typedarray: unsafe extern "C" fn(NapiEnv, NapiValue, *mut bool) -> i32,
    pub(super) create_typedarray:
        unsafe extern "C" fn(NapiEnv, i32, usize, NapiValue, usize, *mut NapiValue) -> i32,
    pub(super) get_typedarray_info: unsafe extern "C" fn(
        NapiEnv,
        NapiValue,
        *mut i32,
        *mut usize,
        *mut *mut c_void,
        *mut NapiValue,
        *mut usize,
    ) -> i32,
    pub(super) create_dataview:
        unsafe extern "C" fn(NapiEnv, usize, NapiValue, usize, *mut NapiValue) -> i32,
    pub(super) is_dataview: unsafe extern "C" fn(NapiEnv, NapiValue, *mut bool) -> i32,
    pub(super) get_dataview_info: unsafe extern "C" fn(
        NapiEnv,
        NapiValue,
        *mut usize,
        *mut *mut c_void,
        *mut NapiValue,
        *mut usize,
    ) -> i32,
    pub(super) create_error:
        unsafe extern "C" fn(NapiEnv, NapiValue, NapiValue, *mut NapiValue) -> i32,
    pub(super) create_type_error:
        unsafe extern "C" fn(NapiEnv, NapiValue, NapiValue, *mut NapiValue) -> i32,
    pub(super) create_range_error:
        unsafe extern "C" fn(NapiEnv, NapiValue, NapiValue, *mut NapiValue) -> i32,
    pub(super) throw: unsafe extern "C" fn(NapiEnv, NapiValue) -> i32,
    pub(super) throw_error: unsafe extern "C" fn(NapiEnv, *const c_char, *const c_char) -> i32,
    pub(super) throw_type_error: unsafe extern "C" fn(NapiEnv, *const c_char, *const c_char) -> i32,
    pub(super) throw_range_error:
        unsafe extern "C" fn(NapiEnv, *const c_char, *const c_char) -> i32,
    pub(super) is_exception_pending: unsafe extern "C" fn(NapiEnv, *mut bool) -> i32,
    pub(super) get_and_clear_last_exception: unsafe extern "C" fn(NapiEnv, *mut NapiValue) -> i32,
    pub(super) is_error: unsafe extern "C" fn(NapiEnv, NapiValue, *mut bool) -> i32,
    pub(super) create_reference: unsafe extern "C" fn(NapiEnv, NapiValue, u32, *mut NapiRef) -> i32,
    pub(super) delete_reference: unsafe extern "C" fn(NapiEnv, NapiRef) -> i32,
    pub(super) reference_ref: unsafe extern "C" fn(NapiEnv, NapiRef, *mut u32) -> i32,
    pub(super) reference_unref: unsafe extern "C" fn(NapiEnv, NapiRef, *mut u32) -> i32,
    pub(super) get_reference_value: unsafe extern "C" fn(NapiEnv, NapiRef, *mut NapiValue) -> i32,
    pub(super) wrap: unsafe extern "C" fn(
        NapiEnv,
        NapiValue,
        *mut c_void,
        Option<NapiFinalize>,
        *mut c_void,
        *mut NapiRef,
    ) -> i32,
    pub(super) unwrap: unsafe extern "C" fn(NapiEnv, NapiValue, *mut *mut c_void) -> i32,
    pub(super) remove_wrap: unsafe extern "C" fn(NapiEnv, NapiValue, *mut *mut c_void) -> i32,
    pub(super) create_object: unsafe extern "C" fn(NapiEnv, *mut NapiValue) -> i32,
    pub(super) define_properties:
        unsafe extern "C" fn(NapiEnv, NapiValue, usize, *const NapiPropertyDescriptor) -> i32,
    pub(super) define_class: unsafe extern "C" fn(
        NapiEnv,
        *const c_char,
        usize,
        Option<NapiCallback>,
        *mut c_void,
        usize,
        *const NapiPropertyDescriptor,
        *mut NapiValue,
    ) -> i32,
    pub(super) create_function: unsafe extern "C" fn(
        NapiEnv,
        *const c_char,
        usize,
        Option<NapiCallback>,
        *mut c_void,
        *mut NapiValue,
    ) -> i32,
    pub(super) set_named_property:
        unsafe extern "C" fn(NapiEnv, NapiValue, *const c_char, NapiValue) -> i32,
    pub(super) get_named_property:
        unsafe extern "C" fn(NapiEnv, NapiValue, *const c_char, *mut NapiValue) -> i32,
    pub(super) get_property:
        unsafe extern "C" fn(NapiEnv, NapiValue, NapiValue, *mut NapiValue) -> i32,
    pub(super) set_property: unsafe extern "C" fn(NapiEnv, NapiValue, NapiValue, NapiValue) -> i32,
    pub(super) has_property: unsafe extern "C" fn(NapiEnv, NapiValue, NapiValue, *mut bool) -> i32,
    pub(super) delete_property:
        unsafe extern "C" fn(NapiEnv, NapiValue, NapiValue, *mut bool) -> i32,
    pub(super) delete_element: unsafe extern "C" fn(NapiEnv, NapiValue, u32, *mut bool) -> i32,
    pub(super) has_own_property:
        unsafe extern "C" fn(NapiEnv, NapiValue, NapiValue, *mut bool) -> i32,
    pub(super) has_named_property:
        unsafe extern "C" fn(NapiEnv, NapiValue, *const c_char, *mut bool) -> i32,
    pub(super) get_property_names: unsafe extern "C" fn(NapiEnv, NapiValue, *mut NapiValue) -> i32,
    pub(super) call_function: unsafe extern "C" fn(
        NapiEnv,
        NapiValue,
        NapiValue,
        usize,
        *const NapiValue,
        *mut NapiValue,
    ) -> i32,
    pub(super) new_instance:
        unsafe extern "C" fn(NapiEnv, NapiValue, usize, *const NapiValue, *mut NapiValue) -> i32,
    pub(super) instanceof: unsafe extern "C" fn(NapiEnv, NapiValue, NapiValue, *mut bool) -> i32,
    pub(super) get_cb_info: unsafe extern "C" fn(
        NapiEnv,
        NapiCallbackInfo,
        *mut usize,
        *mut NapiValue,
        *mut NapiValue,
        *mut *mut c_void,
    ) -> i32,
    pub(super) open_handle_scope: unsafe extern "C" fn(NapiEnv, *mut NapiHandleScope) -> i32,
    pub(super) close_handle_scope: unsafe extern "C" fn(NapiEnv, NapiHandleScope) -> i32,
    pub(super) open_escapable_handle_scope:
        unsafe extern "C" fn(NapiEnv, *mut NapiHandleScope) -> i32,
    pub(super) close_escapable_handle_scope: unsafe extern "C" fn(NapiEnv, NapiHandleScope) -> i32,
    pub(super) escape_handle:
        unsafe extern "C" fn(NapiEnv, NapiHandleScope, NapiValue, *mut NapiValue) -> i32,
    pub(super) create_promise:
        unsafe extern "C" fn(NapiEnv, *mut NapiDeferred, *mut NapiValue) -> i32,
    pub(super) resolve_deferred: unsafe extern "C" fn(NapiEnv, NapiDeferred, NapiValue) -> i32,
    pub(super) reject_deferred: unsafe extern "C" fn(NapiEnv, NapiDeferred, NapiValue) -> i32,
    pub(super) is_promise: unsafe extern "C" fn(NapiEnv, NapiValue, *mut bool) -> i32,
    pub(super) create_async_work: unsafe extern "C" fn(
        NapiEnv,
        NapiValue,
        NapiValue,
        Option<NapiAsyncExecuteCallback>,
        Option<NapiAsyncCompleteCallback>,
        *mut c_void,
        *mut NapiAsyncWork,
    ) -> i32,
    pub(super) delete_async_work: unsafe extern "C" fn(NapiEnv, NapiAsyncWork) -> i32,
    pub(super) queue_async_work: unsafe extern "C" fn(NapiEnv, NapiAsyncWork) -> i32,
    pub(super) cancel_async_work: unsafe extern "C" fn(NapiEnv, NapiAsyncWork) -> i32,
    pub(super) create_threadsafe_function: unsafe extern "C" fn(
        NapiEnv,
        NapiValue,
        NapiValue,
        NapiValue,
        usize,
        usize,
        *mut c_void,
        Option<NapiFinalize>,
        *mut c_void,
        Option<NapiThreadsafeFunctionCallJs>,
        *mut NapiThreadsafeFunction,
    ) -> i32,
    pub(super) get_threadsafe_function_context:
        unsafe extern "C" fn(NapiThreadsafeFunction, *mut *mut c_void) -> i32,
    pub(super) call_threadsafe_function:
        unsafe extern "C" fn(NapiThreadsafeFunction, *mut c_void, i32) -> i32,
    pub(super) acquire_threadsafe_function: unsafe extern "C" fn(NapiThreadsafeFunction) -> i32,
    pub(super) release_threadsafe_function:
        unsafe extern "C" fn(NapiThreadsafeFunction, i32) -> i32,
    pub(super) ref_threadsafe_function:
        unsafe extern "C" fn(NapiEnv, NapiThreadsafeFunction) -> i32,
    pub(super) unref_threadsafe_function:
        unsafe extern "C" fn(NapiEnv, NapiThreadsafeFunction) -> i32,
    pub(super) add_env_cleanup_hook:
        unsafe extern "C" fn(NapiEnv, Option<NapiCleanupHook>, *mut c_void) -> i32,
    pub(super) remove_env_cleanup_hook:
        unsafe extern "C" fn(NapiEnv, Option<NapiCleanupHook>, *mut c_void) -> i32,
    pub(super) get_last_error_info:
        unsafe extern "C" fn(NapiEnv, *mut *const NapiExtendedErrorInfo) -> i32,
    pub(super) get_new_target:
        unsafe extern "C" fn(NapiEnv, NapiCallbackInfo, *mut NapiValue) -> i32,
    pub(super) get_version: unsafe extern "C" fn(NapiEnv, *mut u32) -> i32,
    pub(super) strict_equals: unsafe extern "C" fn(NapiEnv, NapiValue, NapiValue, *mut bool) -> i32,
    pub(super) run_script: unsafe extern "C" fn(NapiEnv, NapiValue, *mut NapiValue) -> i32,
    pub(super) adjust_external_memory: unsafe extern "C" fn(NapiEnv, i64, *mut i64) -> i32,
    pub(super) coerce_to_object: unsafe extern "C" fn(NapiEnv, NapiValue, *mut NapiValue) -> i32,
    pub(super) create_external_arraybuffer: unsafe extern "C" fn(
        NapiEnv,
        *mut c_void,
        usize,
        Option<NapiFinalize>,
        *mut c_void,
        *mut NapiValue,
    ) -> i32,
    pub(super) create_external_buffer: unsafe extern "C" fn(
        NapiEnv,
        usize,
        *mut c_void,
        Option<NapiFinalize>,
        *mut c_void,
        *mut NapiValue,
    ) -> i32,
    pub(super) async_init:
        unsafe extern "C" fn(NapiEnv, NapiValue, NapiValue, *mut NapiAsyncContext) -> i32,
    pub(super) async_destroy: unsafe extern "C" fn(NapiEnv, NapiAsyncContext) -> i32,
    pub(super) make_callback: unsafe extern "C" fn(
        NapiEnv,
        NapiAsyncContext,
        NapiValue,
        NapiValue,
        usize,
        *const NapiValue,
        *mut NapiValue,
    ) -> i32,
    pub(super) open_callback_scope:
        unsafe extern "C" fn(NapiEnv, NapiValue, NapiAsyncContext, *mut NapiCallbackScope) -> i32,
    pub(super) close_callback_scope: unsafe extern "C" fn(NapiEnv, NapiCallbackScope) -> i32,
    pub(super) create_date: unsafe extern "C" fn(NapiEnv, f64, *mut NapiValue) -> i32,
    pub(super) is_date: unsafe extern "C" fn(NapiEnv, NapiValue, *mut bool) -> i32,
    pub(super) get_date_value: unsafe extern "C" fn(NapiEnv, NapiValue, *mut f64) -> i32,
    pub(super) add_finalizer: unsafe extern "C" fn(
        NapiEnv,
        NapiValue,
        *mut c_void,
        Option<NapiFinalize>,
        *mut c_void,
        *mut NapiRef,
    ) -> i32,
    pub(super) create_bigint_int64: unsafe extern "C" fn(NapiEnv, i64, *mut NapiValue) -> i32,
    pub(super) create_bigint_uint64: unsafe extern "C" fn(NapiEnv, u64, *mut NapiValue) -> i32,
    pub(super) create_bigint_words:
        unsafe extern "C" fn(NapiEnv, i32, usize, *const u64, *mut NapiValue) -> i32,
    pub(super) get_value_bigint_int64:
        unsafe extern "C" fn(NapiEnv, NapiValue, *mut i64, *mut bool) -> i32,
    pub(super) get_value_bigint_uint64:
        unsafe extern "C" fn(NapiEnv, NapiValue, *mut u64, *mut bool) -> i32,
    pub(super) get_value_bigint_words:
        unsafe extern "C" fn(NapiEnv, NapiValue, *mut i32, *mut usize, *mut u64) -> i32,
    pub(super) get_all_property_names:
        unsafe extern "C" fn(NapiEnv, NapiValue, i32, i32, i32, *mut NapiValue) -> i32,
    pub(super) set_instance_data:
        unsafe extern "C" fn(NapiEnv, *mut c_void, Option<NapiFinalize>, *mut c_void) -> i32,
    pub(super) get_instance_data: unsafe extern "C" fn(NapiEnv, *mut *mut c_void) -> i32,
    pub(super) detach_arraybuffer: unsafe extern "C" fn(NapiEnv, NapiValue) -> i32,
    pub(super) is_detached_arraybuffer: unsafe extern "C" fn(NapiEnv, NapiValue, *mut bool) -> i32,
    pub(super) type_tag_object: unsafe extern "C" fn(NapiEnv, NapiValue, *const NapiTypeTag) -> i32,
    pub(super) check_object_type_tag:
        unsafe extern "C" fn(NapiEnv, NapiValue, *const NapiTypeTag, *mut bool) -> i32,
    pub(super) object_freeze: unsafe extern "C" fn(NapiEnv, NapiValue) -> i32,
    pub(super) object_seal: unsafe extern "C" fn(NapiEnv, NapiValue) -> i32,
    pub(super) add_async_cleanup_hook: unsafe extern "C" fn(
        NapiEnv,
        Option<NapiAsyncCleanupHook>,
        *mut c_void,
        *mut NapiAsyncCleanupHookHandle,
    ) -> i32,
    pub(super) remove_async_cleanup_hook: unsafe extern "C" fn(NapiAsyncCleanupHookHandle),
    pub(super) node_api_symbol_for:
        unsafe extern "C" fn(NapiEnv, *const c_char, usize, *mut NapiValue) -> i32,
    pub(super) create_syntax_error:
        unsafe extern "C" fn(NapiEnv, NapiValue, NapiValue, *mut NapiValue) -> i32,
    pub(super) throw_syntax_error:
        unsafe extern "C" fn(NapiEnv, *const c_char, *const c_char) -> i32,
    pub(super) get_module_file_name: unsafe extern "C" fn(NapiEnv, *mut *const c_char) -> i32,
    pub(super) create_external_string_latin1: unsafe extern "C" fn(
        NapiEnv,
        *mut c_char,
        usize,
        Option<NapiFinalize>,
        *mut c_void,
        *mut NapiValue,
        *mut bool,
    ) -> i32,
    pub(super) create_external_string_utf16: unsafe extern "C" fn(
        NapiEnv,
        *mut u16,
        usize,
        Option<NapiFinalize>,
        *mut c_void,
        *mut NapiValue,
        *mut bool,
    ) -> i32,
    pub(super) create_property_key_latin1:
        unsafe extern "C" fn(NapiEnv, *const c_char, usize, *mut NapiValue) -> i32,
    pub(super) create_property_key_utf8:
        unsafe extern "C" fn(NapiEnv, *const c_char, usize, *mut NapiValue) -> i32,
    pub(super) create_property_key_utf16:
        unsafe extern "C" fn(NapiEnv, *const u16, usize, *mut NapiValue) -> i32,
    pub(super) create_buffer_from_arraybuffer:
        unsafe extern "C" fn(NapiEnv, NapiValue, usize, usize, *mut NapiValue) -> i32,
    pub(super) get_node_version: unsafe extern "C" fn(NapiEnv, *mut *const NapiNodeVersion) -> i32,
    pub(super) get_uv_event_loop: unsafe extern "C" fn(NapiEnv, *mut *mut c_void) -> i32,
    pub(super) module_register: unsafe extern "C" fn(*mut c_void),
    pub(super) fatal_error: unsafe extern "C" fn(*const c_char, usize, *const c_char, usize) -> !,
    pub(super) fatal_exception: unsafe extern "C" fn(NapiEnv, NapiValue) -> i32,
    pub(super) set_prototype: unsafe extern "C" fn(NapiEnv, NapiValue, NapiValue) -> i32,
    pub(super) create_object_with_properties: unsafe extern "C" fn(
        NapiEnv,
        NapiValue,
        *const NapiValue,
        *const NapiValue,
        usize,
        *mut NapiValue,
    ) -> i32,
    pub(super) post_finalizer:
        unsafe extern "C" fn(NapiEnv, Option<NapiFinalize>, *mut c_void, *mut c_void) -> i32,
    pub(super) create_sharedarraybuffer:
        unsafe extern "C" fn(NapiEnv, usize, *mut *mut c_void, *mut NapiValue) -> i32,
    pub(super) create_external_sharedarraybuffer: unsafe extern "C" fn(
        NapiEnv,
        *mut c_void,
        usize,
        Option<NodeApiNoEnvFinalize>,
        *mut c_void,
        *mut NapiValue,
    ) -> i32,
    pub(super) is_sharedarraybuffer: unsafe extern "C" fn(NapiEnv, NapiValue, *mut bool) -> i32,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub(super) struct NapiPropertyDescriptor {
    pub(super) utf8name: *const c_char,
    pub(super) name: NapiValue,
    pub(super) method: Option<NapiCallback>,
    pub(super) getter: Option<NapiCallback>,
    pub(super) setter: Option<NapiCallback>,
    pub(super) value: NapiValue,
    pub(super) attributes: i32,
    pub(super) data: *mut c_void,
}

pub(super) static NAPI_VM_API_TABLE: NapiVmApiTable = NapiVmApiTable {
    get_undefined: api_get_undefined,
    get_global: api_get_global,
    get_null: api_get_null,
    get_boolean: api_get_boolean,
    coerce_to_bool: api_coerce_to_bool,
    coerce_to_number: api_coerce_to_number,
    coerce_to_string: api_coerce_to_string,
    create_double: api_create_double,
    create_int32: api_create_int32,
    create_uint32: api_create_uint32,
    create_int64: api_create_int64,
    create_string_latin1: api_create_string_latin1,
    create_string_utf8: api_create_string_utf8,
    create_string_utf16: api_create_string_utf16,
    create_symbol: api_create_symbol,
    create_external: api_create_external,
    typeof_value: api_typeof,
    get_value_external: api_get_value_external,
    get_value_double: api_get_value_double,
    get_value_int32: api_get_value_int32,
    get_value_uint32: api_get_value_uint32,
    get_value_int64: api_get_value_int64,
    get_value_bool: api_get_value_bool,
    get_value_string_latin1: api_get_value_string_latin1,
    get_value_string_utf8: api_get_value_string_utf8,
    get_value_string_utf16: api_get_value_string_utf16,
    create_array: api_create_array,
    create_array_with_length: api_create_array_with_length,
    is_array: api_is_array,
    get_array_length: api_get_array_length,
    get_prototype: api_get_prototype,
    get_element: api_get_element,
    set_element: api_set_element,
    has_element: api_has_element,
    create_buffer: api_create_buffer,
    create_buffer_copy: api_create_buffer_copy,
    get_buffer_info: api_get_buffer_info,
    is_buffer: api_is_buffer,
    is_arraybuffer: api_is_arraybuffer,
    create_arraybuffer: api_create_arraybuffer,
    get_arraybuffer_info: api_get_arraybuffer_info,
    is_typedarray: api_is_typedarray,
    create_typedarray: api_create_typedarray,
    get_typedarray_info: api_get_typedarray_info,
    create_dataview: api_create_dataview,
    is_dataview: api_is_dataview,
    get_dataview_info: api_get_dataview_info,
    create_error: api_create_error,
    create_type_error: api_create_type_error,
    create_range_error: api_create_range_error,
    throw: api_throw,
    throw_error: api_throw_error,
    throw_type_error: api_throw_type_error,
    throw_range_error: api_throw_range_error,
    is_exception_pending: api_is_exception_pending,
    get_and_clear_last_exception: api_get_and_clear_last_exception,
    is_error: api_is_error,
    create_reference: api_create_reference,
    delete_reference: api_delete_reference,
    reference_ref: api_reference_ref,
    reference_unref: api_reference_unref,
    get_reference_value: api_get_reference_value,
    wrap: api_wrap,
    unwrap: api_unwrap,
    remove_wrap: api_remove_wrap,
    create_object: api_create_object,
    define_properties: api_define_properties,
    define_class: api_define_class,
    create_function: api_create_function,
    set_named_property: api_set_named_property,
    get_named_property: api_get_named_property,
    get_property: api_get_property,
    set_property: api_set_property,
    has_property: api_has_property,
    delete_property: api_delete_property,
    delete_element: api_delete_element,
    has_own_property: api_has_own_property,
    has_named_property: api_has_named_property,
    get_property_names: api_get_property_names,
    call_function: api_call_function,
    new_instance: api_new_instance,
    instanceof: api_instanceof,
    get_cb_info: api_get_cb_info,
    open_handle_scope: api_open_handle_scope,
    close_handle_scope: api_close_handle_scope,
    open_escapable_handle_scope: api_open_escapable_handle_scope,
    close_escapable_handle_scope: api_close_escapable_handle_scope,
    escape_handle: api_escape_handle,
    create_promise: api_create_promise,
    resolve_deferred: api_resolve_deferred,
    reject_deferred: api_reject_deferred,
    is_promise: api_is_promise,
    create_async_work: api_create_async_work,
    delete_async_work: api_delete_async_work,
    queue_async_work: api_queue_async_work,
    cancel_async_work: api_cancel_async_work,
    create_threadsafe_function: api_create_threadsafe_function,
    get_threadsafe_function_context: api_get_threadsafe_function_context,
    call_threadsafe_function: api_call_threadsafe_function,
    acquire_threadsafe_function: api_acquire_threadsafe_function,
    release_threadsafe_function: api_release_threadsafe_function,
    ref_threadsafe_function: api_ref_threadsafe_function,
    unref_threadsafe_function: api_unref_threadsafe_function,
    add_env_cleanup_hook: api_add_env_cleanup_hook,
    remove_env_cleanup_hook: api_remove_env_cleanup_hook,
    get_last_error_info: api_get_last_error_info,
    get_new_target: api_get_new_target,
    get_version: api_get_version,
    strict_equals: api_strict_equals,
    run_script: api_run_script,
    adjust_external_memory: api_adjust_external_memory,
    coerce_to_object: api_coerce_to_object,
    create_external_arraybuffer: api_create_external_arraybuffer,
    create_external_buffer: api_create_external_buffer,
    async_init: api_async_init,
    async_destroy: api_async_destroy,
    make_callback: api_make_callback,
    open_callback_scope: api_open_callback_scope,
    close_callback_scope: api_close_callback_scope,
    create_date: api_create_date,
    is_date: api_is_date,
    get_date_value: api_get_date_value,
    add_finalizer: api_add_finalizer,
    create_bigint_int64: api_create_bigint_int64,
    create_bigint_uint64: api_create_bigint_uint64,
    create_bigint_words: api_create_bigint_words,
    get_value_bigint_int64: api_get_value_bigint_int64,
    get_value_bigint_uint64: api_get_value_bigint_uint64,
    get_value_bigint_words: api_get_value_bigint_words,
    get_all_property_names: api_get_all_property_names,
    set_instance_data: api_set_instance_data,
    get_instance_data: api_get_instance_data,
    detach_arraybuffer: api_detach_arraybuffer,
    is_detached_arraybuffer: api_is_detached_arraybuffer,
    type_tag_object: api_type_tag_object,
    check_object_type_tag: api_check_object_type_tag,
    object_freeze: api_object_freeze,
    object_seal: api_object_seal,
    add_async_cleanup_hook: api_add_async_cleanup_hook,
    remove_async_cleanup_hook: api_remove_async_cleanup_hook,
    node_api_symbol_for: api_node_symbol_for,
    create_syntax_error: api_create_syntax_error,
    throw_syntax_error: api_throw_syntax_error,
    get_module_file_name: api_get_module_file_name,
    create_external_string_latin1: api_create_external_string_latin1,
    create_external_string_utf16: api_create_external_string_utf16,
    create_property_key_latin1: api_create_property_key_latin1,
    create_property_key_utf8: api_create_property_key_utf8,
    create_property_key_utf16: api_create_property_key_utf16,
    create_buffer_from_arraybuffer: api_create_buffer_from_arraybuffer,
    get_node_version: api_get_node_version,
    get_uv_event_loop: api_get_uv_event_loop,
    module_register: api_module_register,
    fatal_error: api_fatal_error,
    fatal_exception: api_fatal_exception,
    set_prototype: api_set_prototype,
    create_object_with_properties: api_create_object_with_properties,
    post_finalizer: api_post_finalizer,
    create_sharedarraybuffer: api_create_sharedarraybuffer,
    create_external_sharedarraybuffer: api_create_external_sharedarraybuffer,
    is_sharedarraybuffer: api_is_sharedarraybuffer,
};
